/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.atbm.ui.panel;

import com.atbm.data.DataChat;
import com.atbm.logic.ServerRequestManager;
import com.atbm.ui.MainFrame;
import java.awt.Component;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author <a href="https://www.facebook.com/khanhdepzai.pro/">KhanhDzai</a>
 */
public class ChatPanel extends javax.swing.JPanel {

    private String curMemChat;

    private DefaultListModel<String> memOnlineModel = new DefaultListModel<>();

    /**
     * Creates new form HomePanel
     */
    public ChatPanel() {
        initComponents();
        customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMemOnline = new javax.swing.JList<>();
        jButtonChat = new javax.swing.JButton();
        jButtonXoaTinNhan = new javax.swing.JButton();
        jScrollPaneMessageChat = new javax.swing.JScrollPane();
        jPanelMessageChat = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonGui = new javax.swing.JButton();
        jButtonFile = new javax.swing.JButton();
        jLabelThongTinNguoiChat = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chat");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Danh sách người dùng");

        jListMemOnline.setModel(memOnlineModel);
        jListMemOnline.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListMemOnline);

        jButtonChat.setText("chat");
        jButtonChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChatActionPerformed(evt);
            }
        });

        jButtonXoaTinNhan.setText("xóa tin nhắn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonXoaTinNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButtonChat)
                .addGap(18, 18, 18)
                .addComponent(jButtonXoaTinNhan)
                .addContainerGap())
        );

        jPanelMessageChat.setLayout(new javax.swing.BoxLayout(jPanelMessageChat, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMessageChat.setLayout(new BoxLayout(jPanelMessageChat, BoxLayout.Y_AXIS));
        jPanelMessageChat.setAlignmentY(Component.TOP_ALIGNMENT);
        jPanelMessageChat.setAlignmentX(Component.LEFT_ALIGNMENT);
        jScrollPaneMessageChat.setViewportView(jPanelMessageChat);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jButtonGui.setText("Gửi");
        jButtonGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuiActionPerformed(evt);
            }
        });

        jButtonFile.setText("file");

        jLabelThongTinNguoiChat.setText("Đang chat với: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneMessageChat)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonGui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonFile)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelThongTinNguoiChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelThongTinNguoiChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneMessageChat, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonGui, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void customInit() {
        jScrollPaneMessageChat.getVerticalScrollBar().setUnitIncrement(20);
    }

    public void updateMemOnline(String[] mems) {
        memOnlineModel.clear();
        for (var mem : mems) {
            memOnlineModel.addElement(mem);
        }
    }

    public void updateMemOnline(String mem, boolean isOnline) {
        SwingUtilities.invokeLater(() -> {
            if (isOnline) {
                if (memOnlineModel.contains(mem) == false) { // tránh add trùng
                    memOnlineModel.addElement(mem);
                }
            } else {
                memOnlineModel.removeElement(mem);
            }
            this.jListMemOnline.revalidate();
            this.jListMemOnline.repaint();
        });
    }

    public void sendChatFalse() {
        final var componentCount = this.jPanelMessageChat.getComponentCount();
        this.jPanelMessageChat.remove(componentCount - 1);
        this.jPanelMessageChat.revalidate();
        this.jPanelMessageChat.repaint();

        JOptionPane.showConfirmDialog(
                MainFrame.Instance,
                "Tin nhắn vừa gửi đi không thành công, vui lòng thử lại",
                "Thông báo",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE
        );

        // Đợi Swing render xong rồi mới scroll
        SwingUtilities.invokeLater(() -> {
            smoothScrollToBottom(jScrollPaneMessageChat, 300); // scroll trong 300ms
        });
    }


    private void jButtonGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuiActionPerformed

        final var text = jTextArea1.getText();
        if (text == null || text.trim().isEmpty()) {
            return;
        }
        if (this.curMemChat == null) {
            JOptionPane.showConfirmDialog(
                    MainFrame.Instance,
                    "Vui lòng chọn người muốn gửi tin nhắn trước",
                    "Thông báo",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        if (memOnlineModel.contains(this.curMemChat) == false) {
            JOptionPane.showConfirmDialog(
                    MainFrame.Instance,
                    "Người nhận đang ngoại tuyến",
                    "Thông báo",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        MessageBubblePanel bubble = new MessageBubblePanel(text, true);
        jPanelMessageChat.add(bubble);
        jPanelMessageChat.revalidate();
        jPanelMessageChat.repaint();

        DataChat.saveMessage(this.curMemChat, bubble);

        // Đợi Swing render xong rồi mới scroll
        SwingUtilities.invokeLater(() -> {
            smoothScrollToBottom(jScrollPaneMessageChat, 300); // scroll trong 300ms
        });

        jTextArea1.setText("");

        try {
            ServerRequestManager.Instance.sendChatMessage(curMemChat, text);
        } catch (Exception e) {
            e.printStackTrace();
            sendChatFalse();
        }

    }//GEN-LAST:event_jButtonGuiActionPerformed

    private void smoothScrollToBottom(JScrollPane scrollPane, int durationMillis) {
        JScrollBar vertical = scrollPane.getVerticalScrollBar();
        int start = vertical.getValue();
        int end = vertical.getMaximum();
        long startTime = System.nanoTime();

        Timer timer = new Timer(1000 / 60, null); // 60 FPS
        timer.addActionListener(e -> {
            long elapsed = System.nanoTime() - startTime;
            double t = Math.min(1.0, elapsed / (durationMillis * 1_000_000.0)); // t ∈ [0, 1]

            // Easing function: easeOutCubic
            double progress = 1 - Math.pow(1 - t, 3);
            int value = (int) (start + (end - start) * progress);
            vertical.setValue(value);

            if (t >= 1.0) {
                ((Timer) e.getSource()).stop();
            }
        });
        timer.start();
    }

    public void sendMessageToPanel(final String sender, final String text) {

        MessageBubblePanel bubble = new MessageBubblePanel(text, false);
        jPanelMessageChat.add(bubble);
        jPanelMessageChat.revalidate();
        jPanelMessageChat.repaint();

        DataChat.saveMessage(sender, bubble);

        if (memOnlineModel.contains(this.curMemChat) == true) {
            SwingUtilities.invokeLater(() -> {
                smoothScrollToBottom(jScrollPaneMessageChat, 300); // scroll trong 300ms
            });
        } else {
            // TODO: thông báo nhận được tin nhắn mới
        }

    }


    private void jButtonChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChatActionPerformed

        final var memSelected = jListMemOnline.getSelectedValue();
        if (memSelected == null) {
            JOptionPane.showConfirmDialog(
                    MainFrame.Instance,
                    "Vui lòng chọn người muốn nhắn tin",
                    "Thông báo",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        if (memSelected.equals(ServerRequestManager.Instance.getName())) {
            JOptionPane.showConfirmDialog(
                    MainFrame.Instance,
                    "Không thể tự nhắn tin với bản thân",
                    "Thông báo",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        if (memSelected.equals(this.curMemChat)) {
            JOptionPane.showConfirmDialog(
                    MainFrame.Instance,
                    "Đang chat với người này rồi",
                    "Thông báo",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        this.curMemChat = memSelected;
        this.jLabelThongTinNguoiChat.setText("Đang chat với: " + curMemChat);
        System.out.println("set new cur mem chat ?? " + curMemChat);
        this.jPanelMessageChat.removeAll();

        if (DataChat.getData(curMemChat) instanceof List<MessageBubblePanel> datas) {
            for (var data : datas) {
                this.jPanelMessageChat.add(data);
            }
        }

    }//GEN-LAST:event_jButtonChatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChat;
    private javax.swing.JButton jButtonFile;
    private javax.swing.JButton jButtonGui;
    private javax.swing.JButton jButtonXoaTinNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelThongTinNguoiChat;
    private javax.swing.JList<String> jListMemOnline;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMessageChat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneMessageChat;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
